# Generated by Django 3.1.7 on 2021-03-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old', models.CharField(max_length=255, verbose_name='Старая ссылка')),
                ('new', models.CharField(max_length=255, verbose_name='Новая ссылка')),
            ],
        ),
    ]
